package it.vitalegi.rpgboard.be.repository.querybuilder.pg;

import io.vertx.junit5.VertxExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(VertxExtension.class)
public class DeleteStatementTest {
  Logger log = LoggerFactory.getLogger(this.getClass());

  PreparedStatementFactory factory1 =
      PreparedStatementFactory.init()
          .tableName("table1")
          .primaryKey("pk1")
          .primaryKey("pk2")
          .fields("pk1", "pk2", "field1", "field2")
          .autoGenerated("pk1");

  @Test
  void oneTableSomeFields() {
    assertEquals(
        "DELETE FROM table1 RETURNING pk1, field1;",
        factory1.delete().returning().exact(Arrays.asList("pk1", "field1")).build());
  }

  @Test
  void oneTableNoPlaceholder() {
    assertEquals(
        "DELETE FROM table1 RETURNING pk1, pk2, field1, field2;", factory1.delete().build());
  }

  @Test
  void oneTableOnePlaceholder() {
    assertEquals(
        "DELETE FROM table1 WHERE pk1=#{pk1} RETURNING pk1, pk2, field1, field2;",
        factory1.delete().where().isEqualsToPlaceholder("pk1").end().build());
  }

  @Test
  void oneTableTwoPlaceholder() {
    assertEquals(
        "DELETE FROM table1 WHERE pk1=#{pk1} AND pk2=#{pk2} RETURNING pk1, pk2, field1, field2;",
        factory1.delete().where().areEqualToPlaceholder(Arrays.asList("pk1", "pk2")).end().build());
  }
}
