package it.vitalegi.rpgboard.be.repository.querybuilder.pg;

import io.vertx.junit5.VertxExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(VertxExtension.class)
public class UpdateStatementTest {
  Logger log = LoggerFactory.getLogger(this.getClass());

  PreparedStatementFactory factory1 =
      PreparedStatementFactory.init()
          .tableName("table1")
          .primaryKey("pk1")
          .primaryKey("pk2")
          .fields("pk1", "pk2", "field1", "field2")
          .autoGenerated("pk1");

  @Test
  void oneTableSomeFields() {
    assertEquals(
        "UPDATE table1 SET pk2=#{pk2}, field1=#{field1}, field2=#{field2} RETURNING pk1, pk2, field1, field2;",
        factory1.update().setValues().allExcept("pk1").build());
    assertEquals(
        "UPDATE table1 SET pk2=#{pk2}, field1=#{field1}, field2=#{field2} RETURNING pk1, field1;",
        factory1
            .update()
            .setValues()
            .exact(Arrays.asList("pk2", "field1", "field2"))
            .returning()
            .exact(Arrays.asList("pk1", "field1"))
            .build());
  }

  @Test
  void oneTableNoPlaceholder() {
    assertEquals(
        "UPDATE table1 SET pk1=#{pk1}, pk2=#{pk2}, field1=#{field1}, field2=#{field2} RETURNING pk1, pk2, field1, field2;",
        factory1.update().build());
  }

  @Test
  void oneTableOnePlaceholder() {
    assertEquals(
        "UPDATE table1 SET pk1=#{pk1}, pk2=#{pk2}, field1=#{field1}, field2=#{field2} WHERE pk1=#{pk1} RETURNING pk1, pk2, field1, field2;",
        factory1.update().where().isEqualsToPlaceholder("pk1").end().build());
  }

  @Test
  void oneTableTwoPlaceholder() {
    assertEquals(
        "UPDATE table1 SET pk1=#{pk1}, pk2=#{pk2}, field1=#{field1}, field2=#{field2} WHERE pk1=#{pk1} AND pk2=#{pk2} RETURNING pk1, pk2, field1, field2;",
        factory1.update().where().areEqualToPlaceholder(Arrays.asList("pk1", "pk2")).end().build());
  }
}
