package it.vitalegi.rpgboard.be.repository.querybuilder.pg;

import java.util.ArrayList;
import java.util.List;

public class Table {
  protected List<String> primaryKeys;
  protected List<String> autoGenerated;
  protected List<String> fields;
  protected String tableName;

  public Table() {
    primaryKeys = new ArrayList<>();
    autoGenerated = new ArrayList<>();
    fields = new ArrayList<>();
  }

  protected void hardCopy(Table target) {
    target.primaryKeys.addAll(this.primaryKeys);
    target.autoGenerated.addAll(this.autoGenerated);
    target.fields.addAll(this.fields);
    target.tableName = this.tableName;
  }

  public List<String> getPrimaryKeys() {
    return primaryKeys;
  }

  public void setPrimaryKeys(List<String> primaryKeys) {
    this.primaryKeys = primaryKeys;
  }

  public List<String> getAutoGenerated() {
    return autoGenerated;
  }

  public void setAutoGenerated(List<String> autoGenerated) {
    this.autoGenerated = autoGenerated;
  }

  public List<String> getFields() {
    return fields;
  }

  public void setFields(List<String> fields) {
    this.fields = fields;
  }

  public String getTableName() {
    return tableName;
  }

  public void setTableName(String tableName) {
    this.tableName = tableName;
  }
}
