package it.vitalegi.rpgboard.be.data;

import io.vertx.codegen.annotations.DataObject;
import io.vertx.codegen.format.SnakeCase;
import io.vertx.core.buffer.Buffer;
import io.vertx.core.json.JsonObject;
import io.vertx.sqlclient.templates.annotations.Column;
import io.vertx.sqlclient.templates.annotations.RowMapped;
import it.vitalegi.rpgboard.be.repository.querybuilder.pg.Table;
import it.vitalegi.rpgboard.be.repository.querybuilder.pg.TableFactory;

import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

@DataObject(generateConverter = true)
@RowMapped(formatter = SnakeCase.class)
public class Asset {
  public static final String ASSET_ID = "asset_id";
  public static final String GAME_ID = "game_id";
  public static final String NAME = "name";
  public static final String SIZE = "size";
  public static final String METADATA = "metadata";
  public static final String CONTENT_TYPE = "content_type";
  public static final String CONTENT = "content";
  public static final String USER_ID = "user_id";
  public static final String CREATE_DATE = "create_date";
  public static final String LAST_UPDATE_DATE = "last_update";
  public static final Table BUILDER =
      TableFactory.init()
          .tableName("RPG_Asset")
          .primaryKey(ASSET_ID)
          .autoGenerated(ASSET_ID)
          .fields(
              ASSET_ID,
              GAME_ID,
              NAME,
              SIZE,
              METADATA,
              CONTENT_TYPE,
              CONTENT,
              USER_ID,
              CREATE_DATE,
              LAST_UPDATE_DATE)
          .build();

  @Column(name = ASSET_ID)
  UUID assetId;

  @Column(name = GAME_ID)
  UUID gameId;

  @Column(name = NAME)
  String name;

  @Column(name = SIZE)
  Long size;

  @Column(name = CONTENT)
  Buffer content;

  @Column(name = CONTENT_TYPE)
  String contentType;

  @Column(name = METADATA)
  JsonObject metadata;

  @Column(name = USER_ID)
  UUID userId;

  @Column(name = CREATE_DATE)
  OffsetDateTime createDate;

  @Column(name = LAST_UPDATE_DATE)
  OffsetDateTime lastUpdate;

  public static Map<String, Object> map(
      UUID assetId,
      UUID gameId,
      String name,
      Long size,
      JsonObject metadata,
      String contentType,
      Buffer content,
      UUID userId,
      OffsetDateTime createDate,
      OffsetDateTime lastUpdate) {
    Map<String, Object> map = new HashMap<>();
    map.put(ASSET_ID, assetId);
    map.put(GAME_ID, gameId);
    map.put(NAME, name);
    map.put(SIZE, size);
    map.put(METADATA, metadata);
    map.put(CONTENT_TYPE, contentType);
    map.put(CONTENT, content);
    map.put(USER_ID, userId);
    map.put(CREATE_DATE, createDate);
    map.put(LAST_UPDATE_DATE, lastUpdate);

    return map;
  }

  public static Map<String, Object> map(Asset entry) {
    return map(
        entry.getAssetId(),
        entry.getGameId(),
        entry.getName(),
        entry.getSize(),
        entry.getMetadata(),
        entry.getContentType(),
        entry.getContent(),
        entry.getUserId(),
        entry.getCreateDate(),
        entry.getLastUpdate());
  }

  public static Map<String, Object> mapPK(UUID assetId) {
    Map<String, Object> map = new HashMap<>();
    map.put(ASSET_ID, assetId);
    return map;
  }

  public JsonObject toJson() {
    JsonObject json = new JsonObject();
    AssetConverter.toJson(this, json);
    return json;
  }

  public UUID getAssetId() {
    return assetId;
  }

  public void setAssetId(UUID assetId) {
    this.assetId = assetId;
  }

  public UUID getUserId() {
    return userId;
  }

  public void setUserId(UUID userId) {
    this.userId = userId;
  }

  public OffsetDateTime getCreateDate() {
    return createDate;
  }

  public void setCreateDate(OffsetDateTime createDate) {
    this.createDate = createDate;
  }

  public OffsetDateTime getLastUpdate() {
    return lastUpdate;
  }

  public void setLastUpdate(OffsetDateTime lastUpdate) {
    this.lastUpdate = lastUpdate;
  }

  public UUID getGameId() {
    return gameId;
  }

  public void setGameId(UUID gameId) {
    this.gameId = gameId;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Long getSize() {
    return size;
  }

  public void setSize(Long size) {
    this.size = size;
  }

  public Buffer getContent() {
    return content;
  }

  public void setContent(Buffer content) {
    this.content = content;
  }

  public String getContentType() {
    return contentType;
  }

  public void setContentType(String contentType) {
    this.contentType = contentType;
  }

  public JsonObject getMetadata() {
    return metadata;
  }

  public void setMetadata(JsonObject metadata) {
    this.metadata = metadata;
  }

  @Override
  public String toString() {
    return "Asset{"
        + "assetId="
        + assetId
        + ", gameId="
        + gameId
        + ", name='"
        + name
        + '\''
        + ", size="
        + size
        + ", content='"
        + content
        + '\''
        + ", contentType='"
        + contentType
        + '\''
        + ", metadata="
        + metadata
        + ", userId="
        + userId
        + ", createDate="
        + createDate
        + ", lastUpdate="
        + lastUpdate
        + '}';
  }
}
