package it.vitalegi.rpgboard.be.data;

import io.vertx.codegen.annotations.DataObject;
import io.vertx.codegen.format.SnakeCase;
import io.vertx.core.json.JsonObject;
import io.vertx.sqlclient.templates.annotations.Column;
import io.vertx.sqlclient.templates.annotations.RowMapped;
import it.vitalegi.rpgboard.be.repository.querybuilder.pg.Table;
import it.vitalegi.rpgboard.be.repository.querybuilder.pg.TableFactory;

import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

@DataObject(generateConverter = true)
@RowMapped(formatter = SnakeCase.class)
public class BoardElement {

  public static final String ENTRY_ID = "entry_id";
  public static final String BOARD_ID = "board_id";
  public static final String VISIBILITY_POLICY = "visibility_policy";
  public static final String UPDATE_POLICY = "update_policy";
  public static final String CONFIG = "config";
  public static final String PARENT_ID = "parent_id";
  public static final String USER_ID = "user_id";
  public static final String CREATE_DATE = "create_date";
  public static final String LAST_UPDATE_DATE = "last_update";
  public static final Table BUILDER =
      TableFactory.init()
          .tableName("RPG_Board_Element")
          .primaryKey(ENTRY_ID)
          .autoGenerated(ENTRY_ID)
          .fields(
              ENTRY_ID,
              BOARD_ID,
              PARENT_ID,
              CONFIG,
              UPDATE_POLICY,
              VISIBILITY_POLICY,
              USER_ID,
              CREATE_DATE,
              LAST_UPDATE_DATE)
          .build();

  @Column(name = BOARD_ID)
  UUID boardId;

  @Column(name = ENTRY_ID)
  UUID entryId;

  @Column(name = PARENT_ID)
  UUID parentId;

  @Column(name = CONFIG)
  JsonObject config;

  @Column(name = UPDATE_POLICY)
  String updatePolicy;

  @Column(name = VISIBILITY_POLICY)
  String visibilityPolicy;

  @Column(name = USER_ID)
  UUID userId;

  @Column(name = CREATE_DATE)
  OffsetDateTime createDate;

  @Column(name = LAST_UPDATE_DATE)
  OffsetDateTime lastUpdate;

  public static Map<String, Object> map(
      UUID entryId,
      UUID boardId,
      UUID parentId,
      JsonObject config,
      String updatePolicy,
      String visibilityPolicy,
      UUID userId,
      OffsetDateTime createDate,
      OffsetDateTime lastUpdate) {
    Map<String, Object> map = new HashMap<>();
    map.put(ENTRY_ID, entryId);
    map.put(BOARD_ID, boardId);
    map.put(PARENT_ID, parentId);
    map.put(CONFIG, config);
    map.put(UPDATE_POLICY, updatePolicy);
    map.put(VISIBILITY_POLICY, visibilityPolicy);
    map.put(USER_ID, userId);
    map.put(CREATE_DATE, createDate);
    map.put(LAST_UPDATE_DATE, lastUpdate);

    return map;
  }

  public static Map<String, Object> map(BoardElement entry) {
    return map(
        entry.getEntryId(),
        entry.getBoardId(),
        entry.getParentId(),
        entry.getConfig(),
        entry.getUpdatePolicy(),
        entry.getVisibilityPolicy(),
        entry.getUserId(),
        entry.getCreateDate(),
        entry.getLastUpdate());
  }

  public static Map<String, Object> mapPK(UUID entryId) {
    Map<String, Object> map = new HashMap<>();
    map.put(ENTRY_ID, entryId);
    return map;
  }

  public JsonObject toJson() {
    JsonObject json = new JsonObject();
    BoardElementConverter.toJson(this, json);
    return json;
  }

  public UUID getBoardId() {
    return boardId;
  }

  public void setBoardId(UUID boardId) {
    this.boardId = boardId;
  }

  public UUID getEntryId() {
    return entryId;
  }

  public void setEntryId(UUID entryId) {
    this.entryId = entryId;
  }

  public UUID getParentId() {
    return parentId;
  }

  public void setParentId(UUID parentId) {
    this.parentId = parentId;
  }

  public JsonObject getConfig() {
    return config;
  }

  public void setConfig(JsonObject config) {
    this.config = config;
  }

  public String getUpdatePolicy() {
    return updatePolicy;
  }

  public void setUpdatePolicy(String updatePolicy) {
    this.updatePolicy = updatePolicy;
  }

  public String getVisibilityPolicy() {
    return visibilityPolicy;
  }

  public void setVisibilityPolicy(String visibilityPolicy) {
    this.visibilityPolicy = visibilityPolicy;
  }

  public UUID getUserId() {
    return userId;
  }

  public void setUserId(UUID userId) {
    this.userId = userId;
  }

  public OffsetDateTime getCreateDate() {
    return createDate;
  }

  public void setCreateDate(OffsetDateTime createDate) {
    this.createDate = createDate;
  }

  public OffsetDateTime getLastUpdate() {
    return lastUpdate;
  }

  public void setLastUpdate(OffsetDateTime lastUpdate) {
    this.lastUpdate = lastUpdate;
  }

  @Override
  public String toString() {
    return "BoardElement{"
        + "boardId="
        + boardId
        + ", entryId="
        + entryId
        + ", parentId="
        + parentId
        + ", config="
        + config
        + ", updatePolicy='"
        + updatePolicy
        + '\''
        + ", visibilityPolicy='"
        + visibilityPolicy
        + '\''
        + ", userId="
        + userId
        + ", createDate="
        + createDate
        + ", lastUpdate="
        + lastUpdate
        + '}';
  }
}
